### ISSUE TITLE
Integracion con git

### ISSUE THREAD

**Issue by OnderCampos** [Fridaplatform/Frida-CLI#63]
Añadir la capacidad de crear una branch y commit para los cambios realizados por la documentacion

**Comment by AntonioLopezCh** [comment]
Added 2 screens to push to git repositories:
1. The folder path is a repository (it needs the branch name and the commit message).
2. The folder path is not a repository (it creates one from it and pushes the changes to main)

**Comment by AntonioLopezCh** [comment]
- The previously added screens now create and push to their respective repositories
- Pending: Fix bug when worker has an exception and the system still creates the repository

**Comment by AntonioLopezCh** [comment]
- Fixed a bug where a repository was being created even if the document generator didn't find any functions

**Comment by AntonioLopezCh** [comment]
- Added full capability of detecting local changes in current branch and give the user the option to stash the changes and continue or merge the old and new changes for the commit.

**Comment by AntonioLopezCh** [comment]
- You can now select an option to make a commit in the current or a new branch of a local repository.
- You can stash the current changes and let the app push the new ones it makes, or you can keep your changes and add the new ones.
- It detects if your folder is not a repository and allows you to create one (pushes will be made to the main branch).
Pending from merge:
- Add this features for new recipes.
